server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # register-with-eureka,fetch-registry 表明自己为eureka-server
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-server #服务名称
